"""Static coach-library content for RunCoach AI."""

STARTER_COACH_ITEMS = [
    (
        "Breathing Exercise",
        "Box Breathing",
        "A calm breathing pattern for settling nerves before a run.",
        "Breathe in for 4 counts, hold for 4, breathe out for 4, hold for 4. Repeat 4 rounds.",
        "Before a run, after a stressful day, or when the user feels anxious.",
    ),
    (
        "Breathing Exercise",
        "Rhythm Breathing",
        "A simple breathing rhythm for steady easy runs.",
        "Inhale for 3 steps and exhale for 2 steps while keeping the shoulders relaxed.",
        "Easy runs, warmups, and runs where pace feels uneven.",
    ),
    (
        "Stretch",
        "Calf Wall Stretch",
        "A gentle calf stretch for lower-leg tightness.",
        "Place both hands on a wall, step one foot back, keep the heel down, "
        "and hold 20 to 30 seconds per side.",
        "After running, after hills, or when calves feel tight.",
    ),
    (
        "Stretch",
        "Hip Flexor Lunge Stretch",
        "A stretch for the front of the hips after sitting or running.",
        "Step into a lunge, keep the torso tall, lightly tuck the hips, and "
        "hold 20 to 30 seconds per side.",
        "After easy runs, after long sitting, or when stride feels short.",
    ),
    (
        "Running Style",
        "Easy Running",
        "A relaxed style focused on conversation pace and low stress.",
        "Run at a pace where speaking in short sentences feels possible.",
        "Recovery days, base building, and beginner consistency.",
    ),
    (
        "Running Style",
        "Cadence Focus",
        "A form cue that encourages quick, light steps.",
        "Think short steps, quiet feet, and landing under the body instead of reaching forward.",
        "When the user feels heavy, overstrides, or wants smoother form.",
    ),
    (
        "Run Type",
        "Recovery Run",
        "A short, very easy run that supports recovery.",
        "Run 20 to 30 minutes at a comfortable pace and finish feeling better "
        "than when you started.",
        "After hard workouts, low mood, soreness, or poor sleep.",
    ),
    (
        "Run Type",
        "Tempo Run",
        "A comfortably hard effort that builds sustained speed.",
        "Warm up, run 10 to 20 minutes at controlled effort, then cool down.",
        "When the runner has a base and wants to improve pace.",
    ),
    (
        "Timed Run",
        "20 Minute Easy Run",
        "A simple time-based run for consistency.",
        "Run easy for 20 minutes. Ignore distance and keep the effort relaxed.",
        "Busy days, beginner weeks, and recovery days.",
    ),
    (
        "Timed Run",
        "30 Minute Progression",
        "A timed run that gently increases effort.",
        "Run 10 minutes easy, 10 minutes steady, and 10 minutes slightly faster but controlled.",
        "When the user feels good and wants a structured workout.",
    ),
    (
        "Distance Run",
        "1 Mile Benchmark",
        "A short distance run for checking current fitness.",
        "Warm up first, run 1 mile at strong but controlled effort, then cool down.",
        "Occasional progress checks, not every week.",
    ),
    (
        "Distance Run",
        "3 Mile Endurance Run",
        "A steady distance run for building aerobic endurance.",
        "Run 3 miles at easy effort and aim for even pacing from start to finish.",
        "Base building and weeks where the goal is endurance.",
    ),
    (
        "Hydration",
        "Pre-Run Sip",
        "Drink water before you feel thirsty, especially after warm or humid runs.",
        "Take a few calm sips 20 to 30 minutes before movement, then start easy.",
        "Warm days, humid weather, treadmill rooms, or any run longer than usual.",
    ),
    (
        "Hydration",
        "Post-Run Refill",
        "A simple water break helps you shift from effort into recovery.",
        "After a run or walk, drink water slowly and check how your body feels.",
        "Right after workouts, after sweating, or when the next day also has movement.",
    ),
    (
        "Hydration",
        "Electrolyte Check",
        "Longer or hotter sessions may need more than plain water.",
        "For longer warm workouts, consider a normal food or drink with "
        "electrolytes if it already fits your routine.",
        "Long, warm, humid, or sweaty efforts.",
    ),
    (
        "Rest",
        "Rest Counts",
        "A rest day is still training. Recovery is how your body adapts.",
        "Keep the day easy, walk gently if you want, and avoid testing your pace.",
        "After hard runs, poor sleep, soreness, or several active days in a row.",
    ),
    (
        "Rest",
        "Easy Day Rule",
        "Do not stack hard days when your body is asking for quiet.",
        "Follow a hard or stressful run with an easy run, walk, mobility, or rest.",
        "When pace slows, mood is low, or notes mention tired legs.",
    ),
    (
        "Recovery",
        "Leg Check",
        "Recovery starts with noticing what feels tight or heavy.",
        "Before the next workout, walk for one minute and notice calves, hips, and breathing.",
        "Before choosing between running, walking, or resting.",
    ),
    (
        "Recovery",
        "Gentle Reset Walk",
        "Lower the target and keep movement kind.",
        "Walk 10 to 15 minutes with no pace goal, then stretch calves and hips lightly.",
        "Low mood, sore legs, rough days, or the day after a demanding run.",
    ),
    (
        "Stretching",
        "Calf Wall Stretch",
        "A gentle calf stretch for lower-leg tightness.",
        "Place both hands on a wall, step one foot back, keep the heel down, "
        "and hold 20 to 30 seconds per side.",
        "After running, after hills, or when calves feel tight.",
    ),
    (
        "Stretching",
        "Figure Four Stretch",
        "A simple hip stretch for runners and walkers.",
        "Sit tall, cross one ankle over the opposite knee, and lean forward "
        "gently for 20 seconds per side.",
        "After sitting, after walks, or when hips feel stiff.",
    ),
    (
        "Warmups",
        "Five Minute Ramp",
        "Warmups help the first mile feel less surprising.",
        "Walk 2 minutes, jog or march 2 minutes, then add 4 gentle leg swings per side.",
        "Before easy runs, walk-run sessions, or comeback days.",
    ),
    (
        "Warmups",
        "Ankles And Arms",
        "Wake up the small parts before asking for rhythm.",
        "Do 5 ankle circles each way, 5 shoulder rolls, and 30 seconds of relaxed marching.",
        "Before beginner walks, cold starts, or early morning movement.",
    ),
    (
        "Cooldowns",
        "Walk It Down",
        "A cooldown helps the body settle after effort.",
        "Walk 3 to 5 minutes after running, then breathe slowly before checking your pace.",
        "After faster runs, warm weather, or days when the workout felt intense.",
    ),
    (
        "Cooldowns",
        "Finish Fresh",
        "End with control instead of squeezing out one more hard minute.",
        "Use the last 2 minutes to slow down and notice whether breathing is returning to normal.",
        "Every beginner run or walk-run workout.",
    ),
    (
        "Meditation",
        "One Minute Reset",
        "Try one minute of slow breathing before deciding to skip movement completely.",
        "Sit or stand still, inhale slowly, exhale longer, and repeat for 60 seconds.",
        "Bad days, low motivation, or pre-run nerves.",
    ),
    (
        "Meditation",
        "Walking Attention",
        "Let the walk become a simple focus practice.",
        "For 5 minutes, notice your steps, breath, and one sound around you.",
        "Walk and talk resets, recovery walks, and stressful days.",
    ),
    (
        "Gratitude",
        "Body Thank You",
        "Write down one thing your body helped you do today.",
        "After movement, write one sentence starting with: Today my body helped me...",
        "After any workout, especially when the workout was small but honest.",
    ),
    (
        "Gratitude",
        "One Good Mile",
        "Find one good detail even if the run was imperfect.",
        "Name one thing that went okay: a breath, a view, a choice, or simply showing up.",
        "After rough runs, low mood, or comeback weeks.",
    ),
    (
        "Breathing",
        "Soft Shoulder Breath",
        "Relaxed shoulders can make easy movement feel smoother.",
        "Drop your shoulders, inhale for 3 steps, exhale for 3 steps, and repeat for 2 minutes.",
        "Warmups, walks, and moments when breathing feels rushed.",
    ),
    (
        "Breathing",
        "Long Exhale",
        "A longer exhale can help you settle effort.",
        "Inhale normally, then exhale a little longer than usual for 6 relaxed breaths.",
        "Before an easy run, after a rough day, or during a walk break.",
    ),
    (
        "Beginner Walking",
        "Walk First Win",
        "Walking is a real foundation for running.",
        "Walk 10 minutes at a pace where talking feels easy, then stop while you still feel good.",
        "New runners, comeback days, or low-energy days.",
    ),
    (
        "Beginner Walking",
        "Nature Count",
        "Turn a walk into a simple outdoor mission.",
        "Count 3 trees, 2 birds, and 1 safe landmark during your route.",
        "When movement needs to feel calm, playful, and low pressure.",
    ),
    (
        "Easy Runs",
        "Conversation Pace",
        "Easy running should feel like you could speak in short sentences.",
        "Slow down until breathing feels controlled and shoulders stay loose.",
        "Base building, recovery days, and most beginner runs.",
    ),
    (
        "Easy Runs",
        "Short Loop Confidence",
        "A small loop can make consistency easier.",
        "Pick a short route you can repeat without pressure and keep the pace gentle.",
        "Busy days, new habits, or when confidence feels low.",
    ),
    (
        "Motivation",
        "Two Minute Start",
        "Starting is often the hardest part.",
        "Commit to 2 minutes of movement. After that, choose whether to continue or stop.",
        "Low motivation, cold starts, and days when the plan feels too big.",
    ),
    (
        "Motivation",
        "Show Up Small",
        "Small workouts keep the habit alive.",
        "Shrink the workout until it feels doable: shoes on, 10 minutes, easy effort.",
        "Busy days, heavy moods, or comeback weeks.",
    ),
    (
        "Bad Day Reset",
        "Walk And Talk Reset",
        "Had a rough day? Try a 10-minute walk and talk reset.",
        "Walk gently with no performance goal. Talk out loud, voice memo, or "
        "quietly name what you notice.",
        "Stressful days, low mood, or when running feels like too much.",
    ),
    (
        "Bad Day Reset",
        "Survived Today Note",
        "Give yourself credit for staying with the day.",
        "Write one thing you survived today, then choose a gentle movement goal.",
        "Rough days, low confidence, or when you need kindness before effort.",
    ),
    (
        "Sleep",
        "Sleep Supports Pace",
        "Sleep can affect how pace and effort feel.",
        "If sleep was short, lower the goal and keep the workout conversational.",
        "Poor sleep, slow pace days, or unusually heavy legs.",
    ),
    (
        "Sleep",
        "Evening Wind Down",
        "Recovery keeps working after the workout ends.",
        "Try a short stretch, water, and screen-light break before bed when possible.",
        "Evenings after training or before a planned morning run.",
    ),
    (
        "Consistency",
        "Repeatable Beats Perfect",
        "A repeatable plan is better than a dramatic one.",
        "Choose a workout you can imagine doing again next week.",
        "New habits, busy schedules, and beginner training blocks.",
    ),
    (
        "Consistency",
        "Same Day Anchor",
        "A familiar time can make movement easier to remember.",
        "Pair your walk or run with a routine you already do, like morning coffee or after work.",
        "When missed workouts come from forgetting or decision fatigue.",
    ),
    (
        "Pace Awareness",
        "Check Effort First",
        "Pace is useful, but effort explains the story.",
        "Before judging a pace, check weather, route, sleep, mood, and "
        "heart-rate context if available.",
        "When a run looks slower than expected.",
    ),
    (
        "Pace Awareness",
        "Even Start",
        "Many good runs begin slower than the ego wants.",
        "Start the first 5 minutes easier than planned, then settle into rhythm.",
        "Tempo days, benchmark miles, or any run where you usually start too fast.",
    ),
    (
        "Hydration",
        "Desk Bottle Check",
        "Keep hydration visible during the day.",
        "Place a water bottle where you work or study and take a few sips between tasks.",
        "Busy days, warm weather, or when you forget to drink until late.",
    ),
    (
        "Recovery",
        "Feet Up Minute",
        "A tiny recovery pause can calm heavy legs.",
        "Lie down or sit back, elevate your feet for one minute, and breathe slowly.",
        "After long standing, hard workouts, or tired-leg evenings.",
    ),
    (
        "Stretching",
        "Doorway Chest Opener",
        "Running posture benefits from relaxed shoulders and chest.",
        "Place forearms on a doorway, step through gently, and hold 20 seconds.",
        "After desk time, phone posture, or tight upper-body days.",
    ),
    (
        "Warmups",
        "March And Swing",
        "A quick warmup for beginner walk-run sessions.",
        "March in place for 60 seconds while swinging arms relaxed and tall.",
        "Before short walks, easy runs, or low-energy starts.",
    ),
    (
        "Cooldowns",
        "Breath Before Stats",
        "Let your body settle before judging numbers.",
        "After stopping, take 5 slow breaths before checking pace or distance.",
        "Runs where the watch numbers might make you rush your recovery.",
    ),
    (
        "Meditation",
        "Name The Weather",
        "A simple mindful check-in for outdoor movement.",
        "During a walk, name the sky, air, temperature, and one sound around you.",
        "Stressful days or walks where you want to feel more present.",
    ),
    (
        "Gratitude",
        "Route Thank You",
        "Notice one part of your route that helped you move.",
        "Write one short note about a view, sidewalk, song, breeze, or safe path.",
        "After any walk or run, especially familiar routes.",
    ),
    (
        "Beginner Walking",
        "Two Pole Walk",
        "Use landmarks to keep the goal small.",
        "Walk to the next two light poles or corners, then choose whether to continue.",
        "Low motivation days or first steps back after a break.",
    ),
    (
        "Easy Runs",
        "No Chase Rule",
        "Easy days should not become races.",
        "If someone passes you, let them go and keep your breathing calm.",
        "Crowded routes, group runs, or days when ego wants to push.",
    ),
    (
        "Motivation",
        "Future You Note",
        "Give tomorrow's self a small win.",
        "Write one sentence: Tomorrow I will make movement easier by...",
        "Evenings before a planned workout.",
    ),
    (
        "Bad Day Reset",
        "Low Bar Promise",
        "Lowering the goal can keep trust with yourself.",
        "Promise only 5 minutes of gentle movement, then decide what comes next.",
        "Heavy mood, busy days, or when the original workout feels too big.",
    ),
    (
        "Sleep",
        "Morning Honesty",
        "Sleep changes the training plan.",
        "If sleep was rough, choose easy movement and skip pace pressure.",
        "Morning workouts after short or interrupted sleep.",
    ),
    (
        "Consistency",
        "Calendar Dot",
        "Visible streaks make small wins easier to repeat.",
        "Put one dot on a calendar for any walk, run, stretch, or recovery action.",
        "Habit building and weeks where motivation changes day to day.",
    ),
    (
        "Pace Awareness",
        "Talk Test",
        "Your breathing can guide pace better than ego.",
        "If you cannot say a short sentence, slow down until the effort is easy again.",
        "Easy runs, recovery runs, and beginner workouts.",
    ),
    (
        "Running Style",
        "Tall Crown Cue",
        "A simple posture cue for smoother running.",
        "Imagine a string gently lifting the crown of your head while shoulders stay soft.",
        "When form feels collapsed, tired, or tense.",
    ),
    (
        "Run Type",
        "Walk-Run Builder",
        "A beginner-friendly bridge from walking to running.",
        "Alternate 1 minute easy jogging with 2 minutes walking for 18 minutes.",
        "New runners, comeback weeks, or days when continuous running feels too much.",
    ),
    (
        "Timed Run",
        "Ten Minute Save",
        "A short timed session that protects the habit.",
        "Move for 10 minutes only: walk, jog, or mix both, then stop proud.",
        "Busy days, bad weather windows, or low-energy evenings.",
    ),
    (
        "Distance Run",
        "Half Mile Check-In",
        "A short distance target for gentle confidence.",
        "Complete a half mile at easy effort, then decide if one more half mile feels good.",
        "Beginners, comeback days, and careful distance building.",
    ),
    (
        "Hydration",
        "Desk Water Cue",
        "Use normal daily moments as hydration reminders.",
        "Drink a few sips whenever you return to your desk, car, or kitchen.",
        "Between workouts, warm days, or long study and work sessions.",
    ),
    (
        "Hydration",
        "Color Check",
        "A simple check can remind you to drink steadily.",
        "Notice whether you feel dry, headachy, or sluggish, then take a small water break.",
        "Midday, after coffee, after sweating, or before evening movement.",
    ),
    (
        "Recovery",
        "Feet Up Minute",
        "One quiet minute can help you shift into recovery mode.",
        "Sit or lie down, elevate your feet if comfortable, and take 6 slow breaths.",
        "After long standing, hard workouts, or heavy legs.",
    ),
    (
        "Recovery",
        "Soreness Scale",
        "Let soreness guide the next workout choice.",
        "Rate soreness from 1 to 5. If it is 4 or 5, choose walking, mobility, or rest.",
        "The morning after a harder run or a new distance.",
    ),
    (
        "Stretching",
        "Ankle Circles",
        "Small ankle mobility can make the first steps feel smoother.",
        "Circle each ankle 10 times each direction before walking or running.",
        "Before warmups, after sitting, or when feet feel stiff.",
    ),
    (
        "Warmups",
        "March and Swing",
        "A quick warmup for walks or easy runs.",
        "March in place for 60 seconds while swinging arms naturally and breathing easy.",
        "Before beginner walks, treadmill sessions, or short runs.",
    ),
    (
        "Cooldowns",
        "Slow Finish",
        "Ending gently helps your body come down from effort.",
        "Walk the final 3 to 5 minutes and let your breathing settle before stopping.",
        "After every run, especially warm or intense sessions.",
    ),
    (
        "Meditation",
        "One Sound Focus",
        "A tiny mindfulness reset for noisy days.",
        "During a walk, choose one sound and listen to it for 30 seconds without judging it.",
        "Stressful days, walk-and-talk resets, or cooldown walks.",
    ),
    (
        "Gratitude",
        "Body Thank You",
        "Notice one thing your body helped you do.",
        "Write or say: Thank you body for helping me...",
        "After any completed walk, stretch, run, or recovery choice.",
    ),
    (
        "Breathing",
        "Shoulder Drop Breath",
        "Relax tension before checking pace.",
        "Inhale gently, then exhale while letting shoulders drop away from your ears.",
        "When effort feels tight, before hills, or during a bad-day reset.",
    ),
    (
        "Beginner Walking",
        "Three Tree Walk",
        "Turn an easy walk into a friendly outdoor game.",
        "Walk until you spot three trees, then check your breathing and posture.",
        "Beginner days, low motivation, or walk-and-talk resets.",
    ),
    (
        "Beginner Walking",
        "Bird Count Reset",
        "Use attention to make movement feel lighter.",
        "Count birds, sounds, or colors for 5 minutes while keeping the pace gentle.",
        "Stressful days, family walks, or easy recovery movement.",
    ),
    (
        "Easy Runs",
        "Start Slower",
        "The first mile should feel almost too easy.",
        "Begin 30 to 60 seconds slower than your usual easy pace, then settle in.",
        "Runs after rest days, warm weather, or when excitement makes you rush.",
    ),
    (
        "Motivation",
        "Evidence List",
        "Remind yourself that you already show up.",
        "List three times you moved even when conditions were not perfect.",
        "Before a hard week, after missed workouts, or when confidence dips.",
    ),
    (
        "Bad Day Reset",
        "No Score Walk",
        "Some days need kindness instead of performance.",
        "Walk 10 minutes without checking pace, distance, or calories.",
        "Rough moods, overwhelmed days, or when numbers feel discouraging.",
    ),
    (
        "Sleep",
        "Screen Down Buffer",
        "Protect tomorrow's run with a calmer evening.",
        "Put screens away 10 minutes earlier and choose a quiet wind-down cue.",
        "Nights before morning workouts or after late caffeine.",
    ),
    (
        "Consistency",
        "Same Door Cue",
        "Use one location to make the habit automatic.",
        "Place shoes by the same door so the next walk or run starts with less thinking.",
        "Beginner training plans, busy weeks, or habit rebuilding.",
    ),
    (
        "Pace Awareness",
        "Watch Later",
        "Feel the run before judging the numbers.",
        "Run the first 5 minutes by breathing and posture before checking pace.",
        "Easy runs, recovery runs, and runs after stressful days.",
    ),
]

