"""Version 1: existing capstone schema, with legacy SQLite column upgrades.

Keep this migration immutable after release. Add subsequent versions for changes.
"""

from database import is_postgres, table_columns


def schema_execute(connection, query):
    if is_postgres(connection):
        query = query.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        # SQLite REAL stores double precision; PostgreSQL REAL is only 32 bits.
        query = query.replace(" REAL", " DOUBLE PRECISION")
    connection.execute(query)


def upgrade(connection):
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            timezone TEXT NOT NULL DEFAULT 'America/New_York',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    ensure_user_columns(connection)
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            run_date TEXT NOT NULL,
            distance REAL NOT NULL,
            duration REAL NOT NULL,
            pace REAL NOT NULL,
            mood TEXT NOT NULL,
            notes TEXT,
            feedback TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    ensure_run_context_columns(connection)
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS coach_library (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            category TEXT NOT NULL,
            title TEXT NOT NULL,
            description TEXT NOT NULL,
            instructions TEXT NOT NULL,
            recommended_when TEXT NOT NULL
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS agent_messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            agent_name TEXT DEFAULT 'rico',
            sender TEXT NOT NULL,
            message TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    ensure_agent_message_columns(connection)
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS walk_tasks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            category TEXT NOT NULL,
            is_done INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS analyst_uploads (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            original_name TEXT NOT NULL,
            stored_name TEXT NOT NULL,
            status TEXT NOT NULL,
            analysis_message TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS user_memories (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            agent_name TEXT NOT NULL DEFAULT 'shared',
            memory_key TEXT NOT NULL,
            memory_value TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, agent_name, memory_key)
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS planner_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            event_type TEXT NOT NULL DEFAULT 'workout',
            event_date TEXT NOT NULL,
            start_time TEXT NOT NULL,
            duration_minutes INTEGER NOT NULL,
            title TEXT NOT NULL,
            coach TEXT,
            hydration TEXT,
            warmup TEXT,
            main_workout TEXT,
            cooldown TEXT,
            details TEXT,
            notes TEXT,
            source TEXT NOT NULL DEFAULT 'Personal',
            is_completed INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS community_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            creator_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            description TEXT NOT NULL,
            event_type TEXT NOT NULL,
            event_date TEXT NOT NULL,
            event_time TEXT NOT NULL,
            location TEXT NOT NULL,
            pace_group TEXT NOT NULL,
            language TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS event_rsvps (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            event_id INTEGER NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, event_id)
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS health_connections (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            provider TEXT NOT NULL,
            provider_user_id TEXT,
            access_token TEXT,
            refresh_token TEXT,
            token_expires_at TEXT,
            sync_enabled INTEGER DEFAULT 1,
            last_synced_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, provider)
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS imported_activities (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            provider TEXT NOT NULL,
            external_activity_id TEXT NOT NULL,
            activity_type TEXT NOT NULL,
            start_time TEXT NOT NULL,
            end_time TEXT,
            distance REAL NOT NULL,
            duration REAL NOT NULL,
            pace REAL NOT NULL,
            avg_heart_rate INTEGER,
            max_heart_rate INTEGER,
            calories INTEGER,
            steps INTEGER,
            source_name TEXT,
            raw_summary TEXT,
            is_approved INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(provider, external_activity_id)
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS monthly_challenges (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            description TEXT NOT NULL,
            challenge_type TEXT NOT NULL,
            activity_type TEXT NOT NULL,
            target_value REAL NOT NULL,
            unit TEXT NOT NULL,
            start_date TEXT NOT NULL,
            end_date TEXT NOT NULL,
            is_public INTEGER DEFAULT 1,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(title, start_date, end_date)
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS user_challenge_entries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            challenge_id INTEGER NOT NULL,
            joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            completed_at TIMESTAMP,
            UNIQUE(user_id, challenge_id)
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS message_conversations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_low_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            user_high_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CHECK(user_low_id < user_high_id),
            UNIQUE(user_low_id, user_high_id)
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS community_messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            conversation_id INTEGER NOT NULL REFERENCES message_conversations(id) ON DELETE CASCADE,
            sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            body TEXT NOT NULL CHECK(length(body) BETWEEN 1 AND 2000),
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS message_participants (
            conversation_id INTEGER NOT NULL REFERENCES message_conversations(id) ON DELETE CASCADE,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            last_read_message_id INTEGER REFERENCES community_messages(id),
            joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(conversation_id, user_id)
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS user_blocks (
            blocker_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            blocked_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CHECK(blocker_id != blocked_id),
            PRIMARY KEY(blocker_id, blocked_id)
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS message_reports (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            message_id INTEGER NOT NULL REFERENCES community_messages(id) ON DELETE CASCADE,
            reporter_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            reason TEXT NOT NULL CHECK(reason IN ('harassment', 'spam', 'unsafe', 'other')),
            status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open', 'reviewed', 'closed')),
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(message_id, reporter_id)
        )
        """
    )
    schema_execute(connection,
        """
        CREATE TABLE IF NOT EXISTS message_start_attempts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            attempted_at REAL NOT NULL
        )
        """
    )
    schema_execute(connection,
        """CREATE TABLE IF NOT EXISTS progression_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            source_type TEXT NOT NULL, source_id TEXT NOT NULL,
            reason TEXT NOT NULL, xp INTEGER NOT NULL CHECK(xp > 0),
            rule_version TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, source_type, source_id, reason, rule_version)
        )"""
    )
    schema_execute(connection,
        """CREATE TABLE IF NOT EXISTS workout_reflections (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            planner_event_id INTEGER REFERENCES planner_events(id) ON DELETE SET NULL,
            run_id INTEGER REFERENCES runs(id) ON DELETE SET NULL,
            stage TEXT NOT NULL CHECK(stage IN ('pre_run', 'post_run')),
            message TEXT NOT NULL, rico_response TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )"""
    )
    schema_execute(connection,
        """CREATE TABLE IF NOT EXISTS calendar_subscriptions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            token_hash TEXT NOT NULL UNIQUE,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_used_at TIMESTAMP, revoked_at TIMESTAMP
        )"""
    )
    schema_execute(connection,
        "CREATE INDEX IF NOT EXISTS idx_runs_user_date ON runs(user_id, run_date)"
    )
    schema_execute(connection,
        "CREATE INDEX IF NOT EXISTS idx_runs_user_activity_date ON runs(user_id, workout_type, run_date)"
    )
    schema_execute(connection,
        "CREATE INDEX IF NOT EXISTS idx_user_challenge_entries_challenge_user ON user_challenge_entries(challenge_id, user_id)"
    )
    schema_execute(connection,
        "CREATE INDEX IF NOT EXISTS idx_monthly_challenges_dates ON monthly_challenges(start_date, end_date)"
    )
    schema_execute(connection,
        "CREATE INDEX IF NOT EXISTS idx_message_participants_user ON message_participants(user_id, conversation_id)"
    )
    schema_execute(connection,
        "CREATE INDEX IF NOT EXISTS idx_community_messages_conversation ON community_messages(conversation_id, id)"
    )
    schema_execute(connection,
        "CREATE INDEX IF NOT EXISTS idx_community_messages_sender ON community_messages(sender_id, id)"
    )
    schema_execute(connection,
        "CREATE INDEX IF NOT EXISTS idx_user_blocks_blocked ON user_blocks(blocked_id, blocker_id)"
    )
    schema_execute(connection,
        "CREATE INDEX IF NOT EXISTS idx_message_reports_status ON message_reports(status, created_at)"
    )
    schema_execute(connection,
        "CREATE INDEX IF NOT EXISTS idx_message_start_attempts_user_time ON message_start_attempts(user_id, attempted_at)"
    )
    schema_execute(connection, "CREATE INDEX IF NOT EXISTS idx_progression_user_created ON progression_events(user_id, id)")
    schema_execute(connection, "CREATE INDEX IF NOT EXISTS idx_reflections_user_created ON workout_reflections(user_id, id)")
    schema_execute(connection, "CREATE INDEX IF NOT EXISTS idx_calendar_subscriptions_user ON calendar_subscriptions(user_id, revoked_at)")


def ensure_run_context_columns(connection):
    """Add optional context columns to older runs tables."""
    existing_columns = table_columns(connection, "runs")
    context_columns = {
        "weather_summary": "TEXT",
        "temperature_f": "REAL",
        "wind_mph": "REAL",
        "route_type": "TEXT",
        "route_notes": "TEXT",
        "avg_heart_rate": "INTEGER",
        "max_heart_rate": "INTEGER",
        "calories": "INTEGER",
        "steps": "INTEGER",
        "cadence": "INTEGER",
        "source": "TEXT",
        "workout_type": "TEXT",
        "imported_from": "TEXT",
        "end_date": "TEXT",
        "device": "TEXT",
        "user_id": "INTEGER",
    }

    for column_name, column_type in context_columns.items():
        if column_name not in existing_columns:
            schema_execute(connection,
                f"ALTER TABLE runs ADD COLUMN {column_name} {column_type}"
            )

def ensure_user_columns(connection):
    """Add profile preferences to older users tables."""
    existing_columns = table_columns(connection, "users")
    if "timezone" not in existing_columns:
        connection.execute(
            "ALTER TABLE users ADD COLUMN timezone TEXT "
            "NOT NULL DEFAULT 'America/New_York'"
        )
    if "language" not in existing_columns:
        connection.execute(
            "ALTER TABLE users ADD COLUMN language TEXT "
            "NOT NULL DEFAULT 'en'"
        )
    if "accessibility_mode" not in existing_columns:
        connection.execute(
            "ALTER TABLE users ADD COLUMN accessibility_mode TEXT "
            "NOT NULL DEFAULT 'standard'"
        )

def ensure_agent_message_columns(connection):
    """Add agent tracking to older chat tables."""
    existing_columns = table_columns(connection, "agent_messages")

    if "agent_name" not in existing_columns:
        connection.execute(
            "ALTER TABLE agent_messages ADD COLUMN agent_name TEXT DEFAULT 'rico'"
        )
